# params.yaml

data_dir: "../data/"
classes_dir: "../data/classes/"
classes_greyscale_dir: "../data/classes_greyscale/"
classes_greyscale_augmented_dir: "../data/classes_greyscale_augmented/"
classes_augmented_dir: "../data/classes_augmented/"
classes_preprocessed_dir: "../data/classes_preprocessed/"
output_dir: "../data/output/"

# salt and pepper
diff_threshold: 50
min_fraction: 0.01
kernel_size_salt_pepper: 3


#blur
blur_fft_size: 50
blur_fft_threshold: 10

blur_variance_threshold: 100


# brightness
brightness_block_size: 16

brightness_threshold: 30
brightness_kernel_size: (15,15)

brightness_stretch_low_pct: 2
brightness_stretch_high_pct: 98

brightness_gamma_dark: 0.5
brightness_gamma_bright: 2

delta_hsv_fix: 30

fix_gamma_low_contrast: 0.7
fix_gamma_high_contrast: 0.2

# edge detection
canny_sigma: 1.0

# morphological operations
morph_kernel_size: 5
morph_iterations: 1

augmentations:
  flips:
    - horizontal_flip
    - vertical_flip
    - both_flip

  rotations:
    - rotate_45
    - rotate_90
    - rotate_135
    - rotate_225
    - rotate_270
    - rotate_315

  crops:
    - crop_50_percent
    - crop_25_percent
    - crop_10_percent

  blurs:
    - blur_5x5
    - blur_15x15
    - blur_25x25

  salt_peppers:
    - salt_only
    - pepper_only
    - salt_and_pepper

  contrasts:
    - contrast_0.1
    - contrast_0.5
    - contrast_0.75
    - contrast_1
    - contrast_1.5
    - contrast_2
    - contrast_2.5
    - contrast_3

  brightnesses:
    - brightness_-100
    - brightness_-50
    - brightness_-30
    - brightness_-20
    - brightness_-10
    - brightness_0
    - brightness_10
    - brightness_20
    - brightness_30
    - brightness_50
    - brightness_100
    - brightness_150
  
  overlays:
    - overlay_0.1
    - overlay_0.2
    - overlay_0.3
    - overlay_0.4
    - overlay_0.5
    - overlay_0.6
    - overlay_0.7
    - overlay_0.8
    - overlay_0.9
    
  waves:
    - wave_1_45_0.2
    - wave_1_-45_0.2
    - wave_1_90_0.2
    - wave_1_-90_0.2
    - wave_1_180_0.2
    - wave_1_-180_0.2
    - wave_2_45_0.2
    - wave_2_-45_0.2
    - wave_2_90_0.2
    - wave_2_-90_0.2
    - wave_2_180_0.2
    - wave_2_-180_0.2
    - wave_3_45_0.2
    - wave_3_-45_0.2
    - wave_3_90_0.2
    - wave_3_-90_0.2
    - wave_3_180_0.2
    - wave_3_-180_0.2
    - wave_4_45_0.2
    - wave_4_-45_0.2
    - wave_4_90_0.2
    - wave_4_-90_0.2
    - wave_4_180_0.2
    - wave_4_-180_0.2
    - wave_5_45_0.2
    - wave_5_-45_0.2
    - wave_5_90_0.2
    - wave_5_-90_0.2
    - wave_5_180_0.2
    - wave_5_-180_0.2
    - wave_6_45_0.2
    - wave_6_-45_0.2
    - wave_6_90_0.2
    - wave_6_-90_0.2
    - wave_6_180_0.2
    - wave_6_-180_0.2
    - wave_7_45_0.2
    - wave_7_-45_0.2
    - wave_7_90_0.2
    - wave_7_-90_0.2
    - wave_7_180_0.2
    - wave_7_-180_0.2